import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class FileRead {
    void main() throws IOException {
        Path tasksPath = Path.of("tasks.txt");
        String tasks = Files.readString(tasksPath);

        System.out.println(tasks);
        // File generated by Java
        // 1. Do dishes
        // 2. Do laundry
    }
}
