import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class FileWrite {
    void main() {
        Path tasksPath = Path.of("tasks.txt");
        String tasks = """
        File generated by Java
        1. Do dishes
        2. Do laundry
        """;

        try {
            Files.writeString(tasksPath, tasks);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
